import chalk from "chalk";
import logger from "../../.config/logger.js";
import { Visualizer } from "../../core/index.js";
import { spinner } from "../../utils/index.js";

/**
 * Executes the `search` command for the visualizer CLI tool.
 * 
 * This function searches for a specific target (e.g., file or folder name)
 * in the folder structure generated by the `Visualizer` based on the given config.
 *
 * @param {Object} config - Configuration object parsed from CLI arguments.
 * @param {string[]} [args=[]] - Additional arguments; the first argument is used as the search target.
 * @returns {void}
 */
export function run(config, args = []) {
    const visualizer = new Visualizer(config);
    const target = args[0];

    spinner.start(`Searching for "${target}"...`);

    try {
        const result = visualizer.search(target);

        spinner.succeed(
            chalk.bold.green(
                `Found "${target}" in ${result.length} location(s).`
            )
        );
        console.log(result.join("\n"));

        logger.info(chalk.green(`${target} has been found.`));
    } catch (error) {
        spinner.fail(chalk.bold.red(`Failed to search for "${target}".`));
        logger.error(error);
    }
}
